#!/bin/sh
#
# bspwm config by jastronaut
## mostly defaults, with a bunch of startup programs
#

sxhkd &

bspc config border_width 		5
bspc config window_gap 			18
bspc config top_padding 		37
bspc config split_ratio 		0.52
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true
bspc config focus_by_distance 	true
bspc config focus_follows_pointer true

bspc config normal_border_color '#515151'
bspc config focused_border_color '#e8e6df'
bspc config presel_border_color '#b5bd68'
bspc config normal_sticky_border_color '#515151'
bspc config focused_sticky_border_color '#88AAAA'
bspc config urgent_border_color '#D08770'
bspc config presel_feedback_color '#88AAAA'

bspc monitor -d 1 2 3 4 5

bspc rule -a Onboard state=floating flag=sticky border=off
bspc rule -a feh state=floating

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
dunst &
[ ! -s ~/.config/mpd/pid  ] && mpd
feh --bg-fill pictures/wall.png
compton --backend glx --paint-on-overlay --vsync opengl-swc --config ~/.config/candy.conf -b
battery_warning &
panel &
