#! /bin/sh
#
# bspwm config by jastronaut
## mostly defaults, with a bunch of startup programs
#

sxhkd &

bspc config border_width        4
bspc config window_gap         18

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focus_follows_pointer true

bspc config normal_border_color '#515151'
bspc config focused_border_color '#87b1c1'
bspc config presel_border_color '#b5bd68'
bspc config normal_sticky_border_color '#515151'
bspc config focused_sticky_border_color '#87b1c1'
bspc config urgent_border_color '#D08770'
bspc config presel_feedback_color '#87b1c1'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Onboard state=floating flag=sticky
bspc rule -a Gimp state=floating
bspc rule -a Screenkey manage=off

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
mpd
mpc load all
mpc pause
feh --bg-scale ~/pictures/wall.png
compton --backend glx --paint-on-overlay --vsync opengl-swc --config ~/.config/candy.conf -b
dropbox &
./bin/panel &
