#! /bin/sh
#
# bspwm config by jastronaut
## mostly defaults, with a bunch of startup programs
#

sxhkd &

bspc config border_width        4
bspc config window_gap         13

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color '#8FA1B3'
bspc config focused_border_color '#A3BE8C'
bspc config presel_border_color '#b5bd68'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#D08770'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/bokeh.jpg
compton --config ~/.config/candy.conf -b
# redshift -l 34:118 &
./scripts/batstatus &
panel &
rofi -key-run F8